# Generated by Django 5.1.7 on 2025-04-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_livro', models.CharField(max_length=200, verbose_name='Nome do livro')),
                ('nome_do_autor', models.CharField(max_length=350, verbose_name='Nome do autor')),
                ('data_lancamento', models.DateField(verbose_name='Data de lançamento')),
                ('capa_do_livro', models.ImageField(upload_to='livros', verbose_name='Capa do livro')),
                ('estante_do_livro', models.IntegerField(verbose_name='Numeração da estante')),
                ('categoria', models.ManyToManyField(to='app.categoria')),
            ],
        ),
    ]
