# Generated by Django 5.1.7 on 2025-04-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Titulo da sua Duvida')),
                ('descricao', models.CharField(max_length=750, verbose_name='Descição da Duvida')),
            ],
        ),
    ]
